# Generated by Django 2.1.7 on 2019-03-26 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 0, 30, 57, 403846), verbose_name='date published'),
        ),
    ]
