# Generated by Django 2.1.7 on 2019-04-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190405_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 17, 10, 16, 698039), verbose_name='date published'),
        ),
    ]
