# Generated by Django 2.1.7 on 2019-04-11 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190405_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 15, 28, 25, 517671), verbose_name='date published'),
        ),
    ]
