# Generated by Django 2.1.7 on 2019-04-11 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190411_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 15, 45, 25, 626824), verbose_name='date published'),
        ),
    ]
